# Generated by Django 3.0.3 on 2020-02-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1Min ShortFilm', max_length=300)),
                ('description', models.TextField(default='')),
                ('reglink', models.CharField(default='http://www.google.co.in', max_length=200)),
                ('fees', models.IntegerField(default=0)),
                ('contacts', models.TextField(default='[{"name":"Sahil","mob":7012149418}]')),
                ('image', models.FileField(default='https://testhttp1234.blob.core.windows.net/media/about-ritu_ft9zmHG.jpg', upload_to='')),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil'), ('Arch', 'Arch'), ('General', 'General'), ('TH', 'Tinkerhub'), ('BTC', 'Bootcamp')], max_length=10)),
                ('date', models.CharField(default='', max_length=300)),
                ('time', models.CharField(default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1Min ShortFilm', max_length=300)),
                ('description', models.TextField(default='')),
                ('reglink', models.CharField(default='http://www.google.co.in', max_length=200)),
                ('prize', models.IntegerField(default=0)),
                ('fees', models.IntegerField(default=0)),
                ('contacts', models.TextField(default='[{"name":"Sahil","mob":7012149418}]')),
                ('image', models.FileField(default='https://testhttp1234.blob.core.windows.net/media/about-ritu_ft9zmHG.jpg', upload_to='')),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil'), ('Arch', 'Arch'), ('General', 'General'), ('TH', 'Tinkerhub'), ('BTC', 'Bootcamp')], default='CSE', max_length=10)),
                ('rules', models.TextField(default='[]')),
                ('date', models.CharField(default='', max_length=300)),
                ('time', models.CharField(default='', max_length=300)),
                ('online', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
