# Generated by Django 3.0.3 on 2020-02-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preevent',
            field=models.BooleanField(default=False),
        ),
    ]
