# Generated by Django 3.0.3 on 2020-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_preevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contacts',
            field=models.TextField(default='[{"name":"name","mob":0}]'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil'), ('Arch', 'Arch'), ('General', 'General')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contacts',
            field=models.TextField(default='[{"name":"name","mob":0}]'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MCA', 'MCA'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mech', 'Mech'), ('Civil', 'Civil'), ('Arch', 'Arch'), ('General', 'General')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
