# Generated by Django 3.0.3 on 2020-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200225_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='available',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='seats',
            field=models.IntegerField(default=-1),
        ),
    ]
