# Generated by Django 3.0.3 on 2020-02-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0001_initial'),
        ('events', '0005_event_imagefrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='ImageFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automate.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
