# Generated by Django 3.0.3 on 2020-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200228_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='contacts',
            field=models.TextField(default='name:0'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contacts',
            field=models.TextField(default='name:0'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
