# Generated by Django 3.0.3 on 2020-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200301_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reglink',
            field=models.CharField(default='https://ritu20.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='reglink',
            field=models.CharField(default='https://ritu20.com/', max_length=200),
        ),
    ]
