# Generated by Django 3.0.3 on 2020-03-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 4, 14, 3, 46, 755893)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 4, 14, 4, 0, 701873)),
            preserve_default=False,
        ),
    ]
