# Generated by Django 3.0.3 on 2020-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200304_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='misc', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='createDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='createDate',
            field=models.DateTimeField(),
        ),
    ]
