# Generated by Django 3.0.3 on 2020-03-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200305_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Pre-Event', 'Pre-Event'), ('Gaming', 'Gaming'), ('M.A.D', 'M.A.D'), ('Club', 'Club'), ('Misc', 'Misc'), ('Tech', 'Tech'), ('Non-Tech', 'Non-Tech')], default='Misc', max_length=200, null=True),
        ),
    ]
